name: quotes
description: Flutter Task.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  share: ^2.0.1
  flutter_spinkit: ^5.0.0
  provider: ^5.0.0
  http: ^0.13.0
  sqflite: ^1.3.0
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Bitter
      fonts:
        - asset: assets/fonts/Bitter-Bold.ttf
        - asset: assets/fonts/Bitter-Regular.ttf